defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

repos:
- name: Bridge Foundry
  description: Main repository
  url: https://github.com/bridgefoundry/bridgefoundry.github.io

encoding: utf-8
markdown: rdiscount
rdiscount:
  extensions: [smart]
